### ISSUE TITLE
Link to final 404

### ISSUE THREAD

**Issue by philals** [mpolinowski/gatsby-wiki#1]
Hey looks like the link in the title 404s: https://github.com/mpolinowski/mui-gatsby-markdown

Cheers

**Comment by mpolinowski** [comment]
Hey Phil,

thx! I had to take the source private - but I uploaded a scaffolding of the finished wiki here:

https://github.com/mpolinowski/material-ui-gatsby-wiki

It includes the Gatsby/Material-UI base + a React Index page + a Markdown page. There is also Elasticsearch added to the Index page - you can get it to work with:

https://github.com/mpolinowski/elasticsearch-docker

And deploy both with Docker. If you have an issue with something in there, please let me know :)


Mike

**Comment by philals** [comment]
Looks good. Thanks for changing the links!
